version: "2.0"

services:
  fraudshield:
    image: ghcr.io/your-username/fraud-shield:latest
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    expose:
      - port: 8000
        as: 80
        to:
          - global: true

profiles:
  compute:
    fraudshield:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
        storage:
          size: 1Gi

deployment:
  fraudshield:
    profile: compute:fraudshield
    count: 1
